name: app_study
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  get: ^4.6.5
  cloud_firestore: ^4.4.4
  google_fonts: ^4.0.3
  firebase_storage: ^11.0.15
  flutter_zoom_drawer: ^3.0.4+1
  url_launcher: ^6.1.10
  firebase_auth: ^4.2.10
  google_sign_in: ^6.0.2
  flutter_svg: ^2.0.4
  logger: 1.3.0
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  firebase_core: ^2.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0



flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/DB/papers/

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/icons/AppIcons.ttf

