// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASzVQhYIeJzz7vAgmsJ2zCOXos1TKdhHM',
    appId: '1:56273880991:web:479634b919ff5b827c9faa',
    messagingSenderId: '56273880991',
    projectId: 'study-app-b4d65',
    authDomain: 'study-app-b4d65.firebaseapp.com',
    storageBucket: 'study-app-b4d65.appspot.com',
    measurementId: 'G-G6F2DPZKPK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBzogEaD1Q2PIDdIzNEJ2ChWZvZQx_XG8',
    appId: '1:56273880991:android:611be9952dc0e17f7c9faa',
    messagingSenderId: '56273880991',
    projectId: 'study-app-b4d65',
    storageBucket: 'study-app-b4d65.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCoDa6YxyxBj_swfkFVOXLULwfI7PUxZ8',
    appId: '1:56273880991:ios:0563a53f95c22cda7c9faa',
    messagingSenderId: '56273880991',
    projectId: 'study-app-b4d65',
    storageBucket: 'study-app-b4d65.appspot.com',
    iosClientId: '56273880991-ekt2g6c1s8su2qsijm3k67skvrtlgloe.apps.googleusercontent.com',
    iosBundleId: 'com.example.appStudy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCoDa6YxyxBj_swfkFVOXLULwfI7PUxZ8',
    appId: '1:56273880991:ios:0563a53f95c22cda7c9faa',
    messagingSenderId: '56273880991',
    projectId: 'study-app-b4d65',
    storageBucket: 'study-app-b4d65.appspot.com',
    iosClientId: '56273880991-ekt2g6c1s8su2qsijm3k67skvrtlgloe.apps.googleusercontent.com',
    iosBundleId: 'com.example.appStudy',
  );
}
